{
 "title": "Fluent",
 "description": "Fluent",
 "tags": [
  "fluent",
  "logging"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "fluentd",
    "label": "Fluentd",
    "query": "label_values(kube_pod_info{namespace=\"logging\"},pod)"
   },
   {
    "name": "fluentbit",
    "label": "Fluent-Bit",
    "query": "label_values(kube_pod_info{namespace=\"logging\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "k8s nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Fluent-Bit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*logging.*fluentbit.*\"})",
     "legendFormat": "Active Fluent-bit"
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*logging.*fluentd.*\",pod!~\".*config.*\"})"
    }
   ]
  },
  { "title": "Input/Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Input", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 3, "y": 7 } },
  { "title": "Output", "type": "text", "gridPos": { "h": 1, "w": 13, "x": 8, "y": 7 } },
  {
   "title": "Fluent-Bit input record/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluent-Bit output record/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluent-Bit output error/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluent-Bit output retry/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluent-Bit output fail/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total[1m]))"
    }
   ]
  },
  {
   "title": "Fluentd input record/s",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "content": "<br>\n<br>\n<br>\nFluentd does not provide a metric to measure input."
   },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_records[1m]))",
     "legendFormat": "records"
    }
   ]
  },
  {
   "title": "Fluentd output record/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_records[1m]))",
     "legendFormat": "records"
    }
   ]
  },
  {
   "title": "Fluentd output error/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_errors[1m]))"
    }
   ]
  },
  {
   "title": "Fluentd output retry/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count[1m]))"
    }
   ]
  },
  {
   "title": "Fluentd output rollback/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_rollback_count[1m]))",
     "legendFormat": "records"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    { "title": "Fluentd", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
    {
     "title": "$fluentd CPU usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"logging\", pod=~\"$fluentd\", container=~\"fluentd|config-reloader\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "$fluentd memory usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"logging\", pod=~\"$fluentd\", container=~\"fluentd|config-reloader\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    { "title": "Fluent-Bit", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
    {
     "title": "$fluentbit CPU usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"logging\", pod=~\"$fluentbit\", container=\"fluent-bit\"}[1m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "$fluentbit memory Usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"logging\", pod=~\"$fluentbit\", container=\"fluent-bit\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluentd summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output record rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records[1m]))",
       "legendFormat": "Record rate"
      }
     ]
    },
    {
     "title": "Output error rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_num_errors[1m]))",
       "legendFormat": "Error rate"
      }
     ]
    },
    {
     "title": "Output retry/rollback rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_retry_count[1m]))",
       "legendFormat": "Retry rate"
      },
      {
       "expr": "sum(rate(fluentd_output_status_rollback_count[1m]))",
       "legendFormat": "Rollback rate"
      }
     ]
    },
    {
     "title": "Output record rate byt type",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Output record rate by plugin",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records[1m])) by (plugin_id)",
       "legendFormat": "{{ plugin_id }}"
      }
     ]
    },
    {
     "title": "Output buffer queue by type",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Output buffer queue by plugin",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length) by (plugin_id)",
       "legendFormat": "{{ plugin_id }}"
      }
     ]
    },
    {
     "title": "Output buffer size by type",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_total_bytes) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Output buffer size by plugin",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_total_bytes) by (plugin_id)",
       "legendFormat": "{{ plugin_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluentd details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output record rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records{namespace=\"logging\",pod=~\"$fluentd\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Output error rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_num_errors{namespace=\"logging\",pod=~\"$fluentd\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Output retry/rollback rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_retry_count{namespace=\"logging\",pod=~\"$fluentd\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} retry"
      },
      {
       "expr": "sum(rate(fluentd_output_status_rollback_count{namespace=\"logging\",pod=~\"$fluentd\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }} rollback"
      }
     ]
    },
    {
     "title": "Output record rate byt type",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records{namespace=\"logging\",pod=~\"$fluentd\"}[1m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Output record rate by plugin",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_records{namespace=\"logging\",pod=~\"$fluentd\"}[1m])) by (plugin_id)",
       "legendFormat": "{{ plugin_id }}"
      }
     ]
    },
    {
     "title": "Output buffer queue by type",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length{namespace=\"logging\",pod=~\"$fluentd\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Output buffer queue by plugin",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length{namespace=\"logging\",pod=~\"$fluentd\"}) by (plugin_id)",
       "legendFormat": "{{ plugin_id }}"
      }
     ]
    },
    {
     "title": "Output buffer size by type",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_total_bytes{namespace=\"logging\",pod=~\"$fluentd\"}) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Output buffer size by plugin",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_total_bytes{namespace=\"logging\",pod=~\"$fluentd\"}) by (plugin_id)",
       "legendFormat": "{{ plugin_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluentd timekey",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Newest timekey by pod",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "fluentd_status_buffer_newest_timekey"
      }
     ]
    },
    {
     "title": "Newest timekey by type",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "fluentd_status_buffer_newest_timekey"
      }
     ]
    },
    {
     "title": "Newest timekey by plugin",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "fluentd_status_buffer_newest_timekey"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluent-Bit summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output error rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_errors_total[1m]))",
       "legendFormat": "Error rate"
      }
     ]
    },
    {
     "title": "Output retry/fail rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_retries_total[1m]))",
       "legendFormat": "Retry rate"
      },
      {
       "expr": "sum(rate(fluentbit_output_retries_failed_total[1m]))",
       "legendFormat": "Fail rate"
      }
     ]
    },
    {
     "title": "Input record rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_input_records_total[1m]))",
       "legendFormat": "Input record rate"
      }
     ]
    },
    {
     "title": "Output record rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_proc_records_total[1m]))",
       "legendFormat": "Output record rate"
      }
     ]
    },
    {
     "title": "Input byte rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_input_bytes_total[1m]))",
       "legendFormat": "Input byte rate"
      }
     ]
    },
    {
     "title": "Output byte rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentbit_output_proc_bytes_total[1m]))",
       "legendFormat": "Output byte rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluent-Bit details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output error rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_errors_total{namespace=\"logging\",pod=~\"$fluentbit\"}[1m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Output retry/fail rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_retries_total{namespace=\"logging\",pod=~\"$fluentbit\"}[1m])",
       "legendFormat": "Retries - {{ pod }}"
      },
      {
       "expr": "rate(fluentbit_output_retries_failed_total{namespace=\"logging\",pod=~\"$fluentbit\"}[1m])",
       "legendFormat": "Fails - {{ pod }}"
      }
     ]
    },
    {
     "title": "Input record rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_input_records_total{namespace=\"logging\",pod=~\"$fluentbit\"}[1m])",
       "legendFormat": "{{ pod }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Output record rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_proc_records_total{namespace=\"logging\",pod=~\"$fluentbit\"}[1m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Input byte rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_input_bytes_total{namespace=\"logging\",pod=~\"$fluentbit\"}[1m])",
       "legendFormat": "{{ pod }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Output byte rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(fluentbit_output_proc_bytes_total{namespace=\"logging\",pod=~\"$fluentbit\"}[1m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}