{
 "title": "Logging flows",
 "tags": [
  "logging",
  "sbt"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace:",
    "query": "label_values(go_memstats_alloc_bytes,namespace)"
   },
   { "name": "sink", "label": "Sink:", "query": "elasticsearch,gcs,loki" }
  ]
 },
 "panels": [
  {
   "title": "Router outputs to $sink",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fluentd_output_status_buffer_queue_length{type=~\"$sink\", plugin_id=~\"flow:$namespace:.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GCS logs rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".+_gcs_logs_total\"}[1m])) by (exported_namespace)",
     "legendFormat": "{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "LOKI logs rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".+_loki_logs_total\"}[1m])) by (exported_namespace)",
     "legendFormat": "{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "K8S event logs rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(k8s_event_logs_total{event_namespace!=\"\"}[1m])) by (event_namespace)",
     "legendFormat": "{{ event_namespace }}"
    }
   ]
  }
 ]
}