{
 "title": "Loki - SBT custom",
 "tags": [
  "logging",
  "loki",
  "sbt"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)"
   },
   {
    "name": "logql",
    "label": "LogQL filter",
    "query": "`\"level\":\"error\"`"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "INFO counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"info\"[$__interval]))"
    }
   ]
  },
  {
   "title": "WARN counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"warn\"[$__interval]))"
    }
   ]
  },
  {
   "title": "ERROR counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"error\"[$__interval]))"
    }
   ]
  },
  {
   "title": "INFO rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"info\")[1m]))"
    }
   ]
  },
  {
   "title": "WARN rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"warn\")[1m]))"
    }
   ]
  },
  {
   "title": "ERROR rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"error\")[1m]))"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$logql rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(({namespace=\"$namespace\", pod=~\"$pod\"} |~ $logql)[$__interval]))"
      }
     ]
    },
    {
     "title": "$logql logs",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=~\"$pod\"} |~ $logql"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
     "options": {
      "content": "<div style=\"text-align:center\"> For Grafana Loki blog example </div>\n\n\n"
     }
    }
   ]
  }
 ]
}