{
 "title": "Elasticsearch - Index Stats",
 "description": "Elasticsearch index stats dashboard",
 "tags": [
  "elasticsearch",
  "indexers"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
   },
   {
    "name": "index",
    "label": "Index",
    "query": "label_values(elasticsearch_index_stats_get_total{instance=\"$instance\",cluster=\"$cluster\"},index)"
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Documents",
   "type": "singlestat",
   "description": "On primary shards",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_docs_primary{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Data",
   "type": "singlestat",
   "description": "On all shards, both primary and replica",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "singlestat",
   "description": "Total segments of index on all shards\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_count_total{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Segment Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_memory_bytes_total{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_deleted_docs_primary{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (index) (elasticsearch_indices_shared_docs{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Data Primary",
   "type": "singlestat",
   "description": "On primary shards",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Segments Primary",
   "type": "singlestat",
   "description": "Total segments on primary shards of index\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_count_primary{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Segment Memory Primary",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\",cluster=~\"$cluster\",index=~\"$index\"})"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Indexing rate on $index",
   "type": "graph",
   "description": "Indexing rate on index\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\nrate(elasticsearch_index_stats_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval]) / rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Searching rate on $index",
   "type": "graph",
   "description": "Searching rate on index\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps", "label": "ReqRate" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\n(rate(elasticsearch_index_stats_search_query_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n+ rate(elasticsearch_index_stats_search_fetch_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n+ rate(elasticsearch_index_stats_search_scroll_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n+ rate(elasticsearch_index_stats_search_suggest_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n) / rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "All Operations ReqRate on $index",
   "type": "graph",
   "description": "Stacked by y-axis",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_merge_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Merge"
    },
    {
     "expr": "rate(elasticsearch_index_stats_flush_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Flush"
    },
    {
     "expr": "rate(elasticsearch_index_stats_refresh_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Refresh"
    },
    {
     "expr": "rate(elasticsearch_index_stats_warmer_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Warmer"
    },
    {
     "expr": "rate(elasticsearch_index_stats_indexing_delete_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Indexing Delete"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_fetch_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Fetch"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Query"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_scroll_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Scroll"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_suggest_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Suggest"
    },
    {
     "expr": "rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Indexing"
    },
    {
     "expr": "rate(elasticsearch_index_stats_get_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Get"
    }
   ]
  },
  {
   "title": "All Operations Runtime/s on $index",
   "type": "graph",
   "description": "Stacked by y-axis",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_merge_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Merge"
    },
    {
     "expr": "rate(elasticsearch_index_stats_flush_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Flush"
    },
    {
     "expr": "rate(elasticsearch_index_stats_refresh_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Refresh"
    },
    {
     "expr": "rate(elasticsearch_index_stats_warmer_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Warmer"
    },
    {
     "expr": "rate(elasticsearch_index_stats_indexing_delete_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Indexing Delete"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_fetch_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Fetch"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_query_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Query"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_scroll_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Scroll"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_suggest_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Search Suggest"
    },
    {
     "expr": "rate(elasticsearch_index_stats_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Indexing"
    },
    {
     "expr": "rate(elasticsearch_index_stats_get_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(elasticsearch_index_stats_merge_stopped_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Merge Stopped"
    },
    {
     "expr": "rate(elasticsearch_index_stats_merge_throttle_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Merge Throttle"
    },
    {
     "expr": "rate(elasticsearch_index_stats_indexing_throttle_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Indexing Throttle"
    }
   ]
  },
  {
   "title": "Search Rate (req/s)",
   "type": "graph",
   "description": "Search phases: Fetch, Query, Scroll, Suggest\n\nStacked by y-axis",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_search_fetch_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Fetch"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Query"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_scroll_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Scroll"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_suggest_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Suggest"
    }
   ]
  },
  {
   "title": "Operation Rate (req/s)",
   "type": "graph",
   "description": "Stacked by y-axis",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_merge_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Merge"
    },
    {
     "expr": "rate(elasticsearch_index_stats_flush_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Flush"
    },
    {
     "expr": "rate(elasticsearch_index_stats_refresh_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Refresh"
    },
    {
     "expr": "rate(elasticsearch_index_stats_warmer_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Warmer"
    },
    {
     "expr": "rate(elasticsearch_index_stats_indexing_delete_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Indexing Delete"
    },
    {
     "expr": "rate(elasticsearch_index_stats_get_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Get"
    }
   ]
  },
  {
   "title": "Avg. Search Time Execute / Request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_search_fetch_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval]) / \nrate(elasticsearch_index_stats_search_fetch_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Fetch"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_query_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval]) / \nrate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Query"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_scroll_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval]) /\nrate(elasticsearch_index_stats_search_scroll_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Scroll"
    },
    {
     "expr": "rate(elasticsearch_index_stats_search_suggest_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval]) /\nrate(elasticsearch_index_stats_search_suggest_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Suggest"
    }
   ]
  },
  { "title": "Index Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Index Memory - Lucene - $index",
   "type": "graph",
   "description": "+ *Lucene Total*: Total heap memory used by Lucene for current index. This is the sum of other fields for primary and replica shards on this node.\n\n+ *Stored Fields*: Heap memory used by Stored Fields (e.g., _source). This is a part of Lucene Total.. \n\n+ *Doc Values*: Heap memory used by Doc Values. This is a part of Lucene Total.. \n\n+ *Norms*: Heap memory used by Norms (normalization factors for query-time, text scoring). This is a part of Lucene Total.\n\n+ *Terms*: (e.g., text). This is a part of Lucene Total.\n\n+ *Points*: Heap memory used by Points (e.g., numbers, IPs, and geo data). This is a part of Lucene Total.\n\n+ *Fixed Bitsets*: (e.g., text). This is a part of Lucene Total.\n\n+ *Term Vectors*: Heap memory used by Term Vectors. This is a part of Lucene Total.\n\n+ *Version Map*: Heap memory used by Versioning (e.g., updates and deletes). This is NOT a part of Lucene Total.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Stored Fields"
    },
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Doc Values"
    },
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Norms"
    },
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Fixed Bitsets"
    },
    {
     "expr": "elasticsearch_indices_segment_term_vectors_memory_total_bytes{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Term Vectors"
    },
    {
     "expr": "elasticsearch_indices_segment_version_map_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Version Map"
    },
    {
     "expr": "elasticsearch_indices_segment_terms_memory_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Terms"
    },
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Points"
    },
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Lucene Total"
    }
   ]
  },
  {
   "title": "Index Memory - Elasticsearch - $index",
   "type": "graph",
   "description": "+ *Query Cache*: Heap memory used by Query Cache (e.g., cached filters). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Request Cache*: Heap memory used by Request Cache (e.g., instant aggregations). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Fielddata*: Heap memory used by Fielddata (e.g., global ordinals or explicitly enabled fielddata on text fields). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Index Writer*: Heap memory used by the Index Writer. This is NOT a part of Lucene Total.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_index_stats_query_cache_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Query Cache"
    },
    {
     "expr": "elasticsearch_index_stats_request_cache_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Request Cache"
    },
    {
     "expr": "elasticsearch_index_stats_fielddata_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Fielddata"
    },
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_total{instance=\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "Index Writer"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_index_stats_query_cache_misses_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Misses"
      },
      {
       "expr": "elasticsearch_index_stats_query_cache_hits_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Hits"
      },
      {
       "expr": "elasticsearch_index_stats_query_cache_evictions_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Evictions"
      },
      {
       "expr": "elasticsearch_index_stats_query_cache_caches_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Caches"
      },
      {
       "expr": "elasticsearch_index_stats_query_cache_size{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Size"
      }
     ]
    },
    {
     "title": "Query Cache Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_index_stats_query_cache_memory_bytes_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Memory"
      }
     ]
    },
    {
     "title": "Request Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_index_stats_request_cache_misses_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Misses"
      },
      {
       "expr": "elasticsearch_index_stats_request_cache_hits_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Hits"
      },
      {
       "expr": "elasticsearch_index_stats_request_cache_evictions_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Evictions"
      }
     ]
    },
    {
     "title": "Request Cache Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_index_stats_request_cache_memory_bytes_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "Memory"
      }
     ]
    }
   ]
  },
  { "title": "Segment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Segment Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segment_doc_values_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "doc_values"
    },
    {
     "expr": "elasticsearch_indices_segment_fields_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "fields"
    },
    {
     "expr": "elasticsearch_indices_segment_fixed_bit_set_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "fixed_bit_set"
    },
    {
     "expr": "elasticsearch_indices_segment_index_writer_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "index_writer"
    },
    {
     "expr": "elasticsearch_indices_segment_norms_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "norms"
    },
    {
     "expr": "elasticsearch_indices_segment_points_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "points"
    },
    {
     "expr": "elasticsearch_indices_segment_term_vectors_memory_total_bytes{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "term_vectors"
    },
    {
     "expr": "elasticsearch_indices_segment_version_map_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "version_map"
    },
    {
     "expr": "elasticsearch_indices_segment_memory_bytes_total{cluster=\"$cluster\",index=\"$index\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Documents (Primary Shards)",
   "type": "graph",
   "description": "Count of documents with only primary shards on all nodes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_primary{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Documents Rate (Primary Shards)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_primary{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data (Primary Shards)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Documents (All Shards)",
   "type": "graph",
   "description": "Count of documents with all shards on all nodes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Documents Rate (All Shards)",
   "type": "graph",
   "description": "Count of documents with all shards on all nodes",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data (All Shards)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Refresh Total",
     "type": "graph",
     "description": "Total refresh index\n\n***Refreshing*** *is scheduled to flush new docs to disk for making them searchable. Default is `1s`, therefore Elasticsearch is `near-real time`*",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_index_stats_refresh_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments changes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 90 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segment_count_primary{cluster=\"$cluster\",index=\"$index\"}",
       "legendFormat": "segments - primary shards"
      },
      {
       "expr": "elasticsearch_indices_segment_count_total{cluster=\"$cluster\",index=\"$index\"}",
       "legendFormat": "segments - all shards"
      }
     ]
    }
   ]
  }
 ]
}