apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - secret.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  # - svc-monitor.yaml

commonLabels:
  app: postgresql
  group: postgres

commonAnnotations:
  version: "13.1"
  exporterVersion: "v0.8.0"
