apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  namespaceSelector:
    matchNames:
      - postgres
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 14s
