
resources:
  - alertmanager.yaml
  - alertmanagerConfig.yaml
  - podmonitor.yaml
  - probe.yaml
  - prometheus.yaml
  - prometheusrule.yaml
  - servicemonitor.yaml
  - thanosruler.yaml

commonLabels:
  app: prometheus-operator
  domain: monitoring
  group: crds

commonAnnotations:
  version: v0.44.0
  # argocd.argoproj.io/hook: Sync
  # argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/sync-wave: "1"
