{
 "title": "K8S - Networking - kube-dns",
 "description": "Dashboard for Kubernetes kube-dns service that uses SkyDNS",
 "tags": [
  "kubernetes",
  "networking"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(skydns_skydns_dns_cachemiss_count_total, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "SkyDNS: Response Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (le) (irate(skydns_skydns_dns_request_duration_seconds_bucket{pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "SkyDNS: Requests / Cache Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(skydns_skydns_dns_cachemiss_count_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Misses"
    },
    {
     "expr": "sum(rate(skydns_skydns_dns_request_count_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "SkyDNS: Error Count Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cause) (rate(skydns_skydns_dns_error_count_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "DNS Probe Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by (le) (rate(kubedns_probe_kubedns_latency_ms_bucket{pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "dnsmasq: Hits vs Misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubedns_dnsmasq_misses{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Misses"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_hits{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Hits"
    }
   ]
  }
 ]
}