{
 "title": "SBT - Logs - AST alarms",
 "tags": [
  "alerting",
  "sbt",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Gatekeeper Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"ast-gatekeeper(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"info\\\\\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "Exchange Reporter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"ast-exchange-reporter(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "Account Reader Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"ast-account-reader(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "ast-account-reader"
    }
   ]
  },
  {
   "title": "Account Writer Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"ast-account-writer(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  }
 ]
}