{
 "title": "SBT - Logs - DIE + HDP + MST alarms",
 "tags": [
  "alerting",
  "sbt",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "DIE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Collectors Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({domain=\"die\", app=~\"die-exchange-collector(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "Writers Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({domain=\"die\", app=~\"die-data-writer(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "OHLCV Calculator Coinbase Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({domain=\"die\", app=~\"die-ohlcv-calculator-coinbase\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "DIE OHLCV Calculator Coinbase Errors"
    }
   ]
  },
  {
   "title": "OHLCV Filler Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({domain=\"die\", container=\"die-ohlcv-filler\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  { "title": "HDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Reader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"hdp-reader(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  { "title": "MST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Writers Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({domain=\"die\", app=~\"mst-writer(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "MST Writer"
    }
   ]
  },
  {
   "title": "Price Writers Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({domain=\"die\", app=~\"mst-price-writer(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "MST Price Writer"
    }
   ]
  },
  {
   "title": "Reader Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({domain=\"die\", app=~\"mst-reader(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "MST Reader Errors"
    }
   ]
  }
 ]
}