{
 "title": "SBT - Logs - TEE alarms",
 "tags": [
  "alerting",
  "sbt",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Broadcaster Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"tee-broadcaster(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "tee-broadcaster"
    }
   ]
  },
  {
   "title": "Reporter & Executor Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"tee-reporter(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "TEE Reporter"
    },
    {
     "expr": "sum(count_over_time({app=~\"tee-executor(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))",
     "legendFormat": "TEE Executor"
    }
   ]
  },
  {
   "title": "Gatekeeper Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"tee-gatekeeper(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "Engine Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"tee-engine(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "Trigger Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"tee-trigger(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  },
  {
   "title": "Data Service Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"tee-dataservice(.|-)*\"} |= \"\\\\\\\"level\\\\\\\":\\\\\\\"error\\\\\\\"\"[5m]))"
    }
   ]
  }
 ]
}