apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:

  - apiGroups:
    - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      # - prometheus
      - sbt-restricted

  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get
  - nonResourceURLs:
    - /metrics
    verbs:
    - get
