
namespace: monitoring

resources:
  - serviceAccount.yaml
  - clusterRole.yaml
  - clusterRoleBinding.yaml
  - deployment.yaml
  - service.yaml
  - serviceMonitor.yaml

commonLabels:
  app: prometheus-operator
  domain: monitoring
  group: operators
  feature: prometheus
  component: controller

commonAnnotations:
  version: v0.44.0
  # argocd.argoproj.io/hook: Sync
  # argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/sync-wave: "2"
