apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-state-metrics
rules:

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - update
    resourceNames:
      - kube-state-metrics

  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
