
namespace: monitoring

resources:
  - podSecurityPolicy.yaml
  - serviceAccount.yaml
  - clusterRole.yaml
  - clusterRoleBinding.yaml
  - daemonset.yaml
  - service.yaml
  - serviceMonitor.yaml

commonLabels:
  app: node-exporter
  domain: monitoring
  feature: prometheus

commonAnnotations:
  version: v1.0.1
