apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-adapter
rules:

  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      # - prometheus-adapter
      - sbt-restricted

  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
      - pods
      - services
    verbs:
      - get
      - list
      - watch
