
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: go-postgres
  group: postgres

commonAnnotations:
  container: "bygui86/go-postgres:latest"
