{
 "title": "Event exporter",
 "tags": [
  "monitoring",
  "k8s",
  "events"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "targets": [
      { "expr": "event_exporter_build_info" }
     ]
    }
   ]
  },
  { "title": "Event count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Events by kind",
   "type": "graph",
   "description": "Count of kubernetes event that was seen for the last hour. The metric value is the same as the count property of Event object in the cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_event_count) by (involved_object_kind)",
     "legendFormat": "{{ involved_object_kind }}"
    }
   ]
  },
  {
   "title": "Events by namespace",
   "type": "graph",
   "description": "Count of kubernetes event that was seen for the last hour. The metric value is the same as the count property of Event object in the cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_event_count{involved_object_kind!~\"Node|Endpoints\"}) by (involved_object_namespace)",
     "legendFormat": "{{ involved_object_namespace }}"
    }
   ]
  },
  {
   "title": "Events by object",
   "type": "table",
   "description": "Count of kubernetes event that was seen for the last hour. The metric value is the same as the count property of Event object in the cluster.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "kube_event_count" }
   ]
  }
 ]
}