apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
spec:
  clusterIP: None
  selector:
    app: prometheus-operator
    component: controller
  ports:
    # - name: http
    #   port: 8080
    #   targetPort: http
    - name: https
      port: 8443
      targetPort: https
