{
 "title": "K8S - Resources - Cluster - Summary",
 "description": "Kubernetes cluster summary",
 "tags": [
  "kubernetes",
  "resources"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(machine_memory_bytes,node)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_network_receive_bytes_total,namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",node=~\"$node\"}[1m])) / sum(machine_cpu_cores{node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",node=~\"$node\"}) / sum(machine_memory_bytes{node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\"}) / sum(container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",node=~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{node=~\"$node\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{node=~\"$node\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "By NAMESPACE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\",namespace=~\"$namespace\"}[1m])) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\",node=~\"$node\",namespace=~\"$namespace\"}) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",node=~\"$node\",namespace=~\"$namespace\"}[1m])) by (namespace)",
       "legendFormat": "Received by {{ namespace }}"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",node=~\"$node\",namespace=~\"$namespace\"}[1m])) by (namespace)",
       "legendFormat": "Sent by {{ namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By POD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\",node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "Received by {{ pod }}"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",node=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (pod)",
       "legendFormat": "Sent by {{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}