
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  # - svc-monitor.yaml

commonLabels:
  app: go-metrics
  group: metrics

commonAnnotations:
  container: "bygui86/go-metrics:latest"
