apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  labels:
    app: grafana
data:
  # general
  GF_INSTALL_PLUGINS: "grafana-kubernetes-app,camptocamp-prometheus-alertmanager-datasource,grafana-piechart-panel,grafana-polystat-panel,agenty-flowcharting-panel"
  
  # datasources
  PROMETHEUS_URL: "http://prometheus.monitoring.svc.cluster.local:9090"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:

    - name: prometheus
      type: prometheus
      orgId: 1
      url: $PROMETHEUS_URL
      access: proxy
      isDefault: true
      version: 1
      editable: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  dashboards.yaml: |-
    apiVersion: 1

    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 300
        options:
          path: "/etc/dashboards"
          foldersFromFilesStructure: true
