apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-grafana
  namespace: monitoring
  labels:
    app: grafana
    domain: monitoring
    group: dashboards
    feature: grafana
    component: grafana
    type: standard
    expandable: "true"
  annotations:
    version: "7.3.4"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  storageClassName: standard-expandable
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
