apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  labels:
    app: rollout-bluegreen
    role: active
spec:
  selector:
    app: rollout-bluegreen
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
  labels:
    app: rollout-bluegreen
    role: preview
spec:
  selector:
    app: rollout-bluegreen
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
