{
 "title": "cert-manager",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [
  "security",
  "certificates"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(exported_namespace)"
   },
   {
    "name": "Certificate",
    "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"},name) "
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controllers sync call counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "certmanager_controller_sync_call_count",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Time Left",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc( sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"} - time()) BY (name,exported_namespace) )",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status) BY (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"} - time()) BY (name,exported_namespace)",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "ACME Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall requests per 2m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(certmanager_http_acme_client_request_count)"
      }
     ]
    },
    {
     "title": "/directory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/directory\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/cert",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/cert\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/new-acct",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-acct\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/order",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/order\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/new-order",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-order\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/authz-v3",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/authz-v3\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/chall-v3",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/chall-v3\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "/acme/finalize",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/finalize\"}[2m])) BY (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  }
 ]
}