{
 "title": "DIE - Pressure",
 "tags": [
  "domains",
  "die",
  "sbt"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "kafka_app_name", "query": "strimzi-cluster" },
   { "name": "cassandra_namespace", "query": "die" },
   {
    "name": "cassandra_datacenter_name",
    "query": "label_values(cassandra_stats{namespace=\"$cassandra_namespace\",name=\"java:lang:memory:heapmemoryusage:used\"}, datacenter)"
   },
   {
    "name": "cassandra_cluster_name",
    "query": "label_values(cassandra_stats{namespace=\"$cassandra_namespace\",datacenter=\"$cassandra_datacenter_name\",name=\"java:lang:memory:heapmemoryusage:used\"}, cluster)"
   },
   { "name": "cassandra_keyspace", "query": "market_data" },
   {
    "name": "cassandra_metric_prefix",
    "query": "org:apache:cassandra:metrics:table"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "COLLECTORS events rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(collector_trade_event_published_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "KAFKA events rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "TODO - WRITERS events rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(writer_ohlcv_event_saved_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(writer_ticker_event_saved_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(writer_trade_event_saved_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "Cassandra writes rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ohlcv\"})",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ticker_updated\"})",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"perpetual_swap\"})",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "OHLCV pressure",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
     "legendFormat": "ohlcv-collectors"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ohlcv\"})",
     "legendFormat": "ohlcv-cassandra"
    }
   ]
  },
  {
   "title": "TICKER pressure",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
     "legendFormat": "ticker-collectors"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ticker_updated\"})",
     "legendFormat": "ticker-cassandra"
    }
   ]
  },
  {
   "title": "TRADE pressure",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(collector_trade_event_published_total[1m]))",
     "legendFormat": "trade-collectors"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
     "legendFormat": "trade-cassandra"
    }
   ]
  },
  {
   "title": "PERPETUAL pressure",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
     "legendFormat": "perpetual-collectors"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"perpetual_swap\"})",
     "legendFormat": "perpetual-cassandra"
    }
   ]
  },
  {
   "title": "OHLCV pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collectors events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
       "legendFormat": "ohlcv"
      }
     ]
    },
    {
     "title": "Kafka events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1m]))",
       "legendFormat": "ohlcv"
      }
     ]
    },
    {
     "title": "Writers events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_ohlcv_event_saved_total[1m]))",
       "legendFormat": "ohlcv"
      }
     ]
    },
    {
     "title": "Cassandra writes rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ohlcv\"})",
       "legendFormat": "ohlcv"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
       "legendFormat": "ohlcv-collectors"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1m]))",
       "legendFormat": "ohlcv-kafka"
      }
     ]
    },
    {
     "title": "kafka vs writers",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1m]))",
       "legendFormat": "ohlcv-kafka"
      },
      {
       "expr": "sum(rate(writer_ohlcv_event_saved_total[1m]))",
       "legendFormat": "ohlcv-writers"
      }
     ]
    },
    {
     "title": "writers vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_ohlcv_event_saved_total[1m]))",
       "legendFormat": "ohlcv-writers"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ohlcv\"})",
       "legendFormat": "ohlcv-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
       "legendFormat": "ohlcv-collectors"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ohlcv\"})",
       "legendFormat": "ohlcv-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_ohlcv_event_published_total[1m])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1m]))",
       "legendFormat": "ohlcv-delta"
      },
      {
       "expr": "sum(rate(collector_ohlcv_event_published_total[1h])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1h]))",
       "legendFormat": "ohlcv-pace"
      }
     ]
    },
    {
     "title": "kafka vs writers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1m])) - sum(rate(writer_ohlcv_event_saved_total[1m]))",
       "legendFormat": "ohlcv-delta"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ohlcv.sampled\"}[1h])) - sum(rate(writer_ohlcv_event_saved_total[1h]))",
       "legendFormat": "ohlcv-pace"
      }
     ]
    },
    {
     "title": "writers vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_ohlcv_event_saved_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ohlcv\"})",
       "legendFormat": "ohlcv-delta"
      },
      {
       "expr": "sum(rate(writer_ohlcv_event_saved_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"ohlcv\"}[1h]))",
       "legendFormat": "ohlcv-pace"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_ohlcv_event_published_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ohlcv\"})",
       "legendFormat": "ohlcv-delta"
      },
      {
       "expr": "sum(rate(collector_ohlcv_event_published_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"ohlcv\"}[1h]))",
       "legendFormat": "ohlcv-pace"
      }
     ]
    }
   ]
  },
  {
   "title": "TICKER pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collectors events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
       "legendFormat": "ticker"
      }
     ]
    },
    {
     "title": "Kafka events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1m]))",
       "legendFormat": "ticker"
      }
     ]
    },
    {
     "title": "Writers events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_ticker_event_saved_total[1m]))",
       "legendFormat": "ticker"
      }
     ]
    },
    {
     "title": "Cassandra writes rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ticker_updated\"})",
       "legendFormat": "ticker"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
       "legendFormat": "ticker-collectors"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1m]))",
       "legendFormat": "ticker-kafka"
      }
     ]
    },
    {
     "title": "kafka vs writers",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1m]))",
       "legendFormat": "ticker-kafka"
      },
      {
       "expr": "sum(rate(writer_ticker_event_saved_total[1m]))",
       "legendFormat": "ticker-writers"
      }
     ]
    },
    {
     "title": "writers vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_ticker_event_saved_total[1m]))",
       "legendFormat": "ticker-writers"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ticker_updated\"})",
       "legendFormat": "ticker-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
       "legendFormat": "ticker-collectors"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ticker_updated\"})",
       "legendFormat": "ticker-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_ticker_event_published_total[1m])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1m]))",
       "legendFormat": "ticker-delta"
      },
      {
       "expr": "sum(rate(collector_ticker_event_published_total[1h])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1h]))",
       "legendFormat": "ticker-pace"
      }
     ]
    },
    {
     "title": "kafka vs writers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1m])) - sum(rate(writer_ticker_event_saved_total[1m]))",
       "legendFormat": "ticker-delta"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.ticker.updated\"}[1h])) - sum(rate(writer_ticker_event_saved_total[1h]))",
       "legendFormat": "ticker-pace"
      }
     ]
    },
    {
     "title": "writers vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_ticker_event_saved_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ticker_updated\"})",
       "legendFormat": "ticker-delta"
      },
      {
       "expr": "sum(rate(writer_ticker_event_saved_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"ticker_updated\"}[1h]))",
       "legendFormat": "ticker-pace"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_ticker_event_published_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"ticker_updated\"})",
       "legendFormat": "ticker-delta"
      },
      {
       "expr": "sum(rate(collector_ticker_event_published_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"ticker_updated\"}[1h]))",
       "legendFormat": "ticker-pace"
      }
     ]
    }
   ]
  },
  {
   "title": "TRADE pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collectors events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_trade_event_published_total[1m]))",
       "legendFormat": "trade"
      }
     ]
    },
    {
     "title": "Kafka events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1m]))",
       "legendFormat": "trade"
      }
     ]
    },
    {
     "title": "Writers events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_trade_event_saved_total[1m]))",
       "legendFormat": "trade"
      }
     ]
    },
    {
     "title": "Cassandra writes rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
       "legendFormat": "trade"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_trade_event_published_total[1m]))",
       "legendFormat": "trade-collectors"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1m]))",
       "legendFormat": "trade-kafka"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_trade_event_published_total[1m]))",
       "legendFormat": "trade-collectors"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1m]))",
       "legendFormat": "trade-kafka"
      }
     ]
    },
    {
     "title": "writers vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_trade_event_saved_total[1m]))",
       "legendFormat": "trade-writers"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
       "legendFormat": "trade-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_trade_event_published_total[1m]))",
       "legendFormat": "trade-collectors"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
       "legendFormat": "trade-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_trade_event_published_total[1m])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1m]))",
       "legendFormat": "trade-delta"
      },
      {
       "expr": "sum(rate(collector_trade_event_published_total[1h])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1h]))",
       "legendFormat": "trade-pace"
      }
     ]
    },
    {
     "title": "kafka vs writers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1m])) - sum(rate(writer_trade_event_saved_total[1m]))",
       "legendFormat": "trade-delta"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.trade.executed\"}[1h])) - sum(rate(writer_trade_event_saved_total[1h]))",
       "legendFormat": "trade-pace"
      }
     ]
    },
    {
     "title": "writers vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_trade_event_saved_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
       "legendFormat": "trade-delta"
      },
      {
       "expr": "sum(rate(writer_trade_event_saved_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"trade_executed\"}[1h]))",
       "legendFormat": "trade-pace"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_trade_event_published_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
       "legendFormat": "trade-delta"
      },
      {
       "expr": "sum(rate(collector_trade_event_published_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"trade_executed\"}[1h]))",
       "legendFormat": "trade-pace"
      }
     ]
    }
   ]
  },
  {
   "title": "TODO - PERPETUAL pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collectors events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Kafka events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "TODO - Writers events rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Cassandra writes rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"perpetual_swap\"})",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
       "legendFormat": "perpetual-collectors"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1m]))",
       "legendFormat": "perpetual-kafka"
      }
     ]
    },
    {
     "title": "TODO - kafka vs writers",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1m]))",
       "legendFormat": "perpetual-kafka"
      },
      {
       "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
       "legendFormat": "perpetual-writers"
      }
     ]
    },
    {
     "title": "TODO - writers vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
       "legendFormat": "perpetual-writers"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"perpetual_swap\"})",
       "legendFormat": "perpetual-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
       "legendFormat": "perpetual-collectors"
      },
      {
       "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"perpetual_swap\"})",
       "legendFormat": "perpetual-cassandra"
      }
     ]
    },
    {
     "title": "collectors vs kafka",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1m]))",
       "legendFormat": "perpetual-delta"
      },
      {
       "expr": "sum(rate(collector_perpetual_swap_event_published_total[1h])) - sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1h]))",
       "legendFormat": "perpetual-pace"
      }
     ]
    },
    {
     "title": "TODO - kafka vs writers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1m])) - sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
       "legendFormat": "perpetual-delta"
      },
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$kafka_app_name\",topic=\"die.perpetual.swap.updated\"}[1h])) - sum(rate(writer_perpetual_swap_event_saved_total[1h]))",
       "legendFormat": "perpetual-pace"
      }
     ]
    },
    {
     "title": "TODO - writers vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"trade_executed\"})",
       "legendFormat": "perpetual-delta"
      },
      {
       "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"trade_executed\"}[1h]))",
       "legendFormat": "perpetual-pace"
      }
     ]
    },
    {
     "title": "collectors vs db",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m])) - sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:oneminuterate\",table=\"perpetual_swap\"})",
       "legendFormat": "perpetual-delta"
      },
      {
       "expr": "sum(rate(collector_perpetual_swap_event_published_total[1h])) - sum(rate(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:writelatency:count\",table=\"perpetual_swap\"}[1h]))",
       "legendFormat": "perpetual-pace"
      }
     ]
    }
   ]
  }
 ]
}