{
 "title": "DIE - Collectors",
 "tags": [
  "domains",
  "die",
  "sbt"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open WS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(collector_open_ws_connections_number, \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
     "legendFormat": "{{ exchange }}"
    }
   ]
  },
  {
   "title": "Polling jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(collector_active_http_polling_cronjobs_number, \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
     "legendFormat": "{{ exchange }}"
    }
   ]
  },
  {
   "title": "WS in error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(collector_ws_connections_in_error_number, \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
     "legendFormat": "{{ exchange }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(rate(collector_error_event_published_total[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
     "legendFormat": "{{ exchange }}"
    }
   ]
  },
  {
   "title": "Retries rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(rate(collector_event_publish_retries_total[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
     "legendFormat": "{{ exchange }}"
    }
   ]
  },
  {
   "title": "Reconnection rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(rate(collector_ws_reconnections_total[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
     "legendFormat": "{{ exchange }}"
    }
   ]
  },
  {
   "title": "Collecting details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received OHLCV",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_ohlcv_event_received_total{job!~\".*-ticker|.*-trade|.*-perpetual\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    },
    {
     "title": "Received TICKER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_ticker_event_received_total{job!~\".*-ohlcv|.*-trade|.*-perpetual\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    },
    {
     "title": "Received TRADE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_trade_event_received_total{job!~\".*-ohlcv|.*-ticker|.*-perpetual\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    },
    {
     "title": "Received PERPETUAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_perpetual_swap_event_received_total{job!~\".*-ohlcv|.*-ticker|.*-trade\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Publishing details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Published OHLCV",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_ohlcv_event_published_total{job!~\".*-ticker|.*-trade|.*-perpetual\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    },
    {
     "title": "Published TICKER",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_ticker_event_published_total{job!~\".*-ohlcv|.*-trade|.*-perpetual\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    },
    {
     "title": "Published TRADE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_trade_event_published_total{job!~\".*-ohlcv|.*-ticker|.*-perpetual\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    },
    {
     "title": "Published PERPETUAL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(collector_perpetual_swap_event_published_total{job!~\".*-ohlcv|.*-ticker|.*-trade\"}[1m]), \"exchange\", \"$1\", \"job\", \"die-exchange-collector-(.*)\")",
       "legendFormat": "{{ exchange }}"
      }
     ]
    }
   ]
  }
 ]
}