{
 "title": "DIE - Latency",
 "tags": [
  "domains",
  "die",
  "sbt"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "label_values(global_event_handling_time_milliseconds_bucket,source)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "99th percentile",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "ticker"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "trade"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "Average duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"ohlcv\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"ohlcv\",source=\"$source\"}[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"ticker\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"ticker\",source=\"$source\"}[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"trade\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"trade\",source=\"$source\"}[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"perpetual\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"perpetual\",source=\"$source\"}[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "99th percentile",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "ticker"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "trade"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "Average duration",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"ohlcv\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"ohlcv\",source=\"$source\"}[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"ticker\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"ticker\",source=\"$source\"}[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"trade\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"trade\",source=\"$source\"}[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(global_event_handling_time_milliseconds_sum{dataset=\"perpetual\",source=\"$source\"}[1m])) / sum(rate(global_event_handling_time_milliseconds_count{dataset=\"perpetual\",source=\"$source\"}[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "DIE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "99th percentile",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ticker"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "trade"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"ohlcv\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"ohlcv\",source=\"$source\"}[1m]))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"ticker\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"ticker\",source=\"$source\"}[1m]))",
       "legendFormat": "ticker"
      },
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"trade\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"trade\",source=\"$source\"}[1m]))",
       "legendFormat": "trade"
      },
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"perpetual\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"perpetual\",source=\"$source\"}[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "99th percentile",
     "type": "graph",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ticker"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "trade"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(die_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "graph",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"ohlcv\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"ohlcv\",source=\"$source\"}[1m]))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"ticker\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"ticker\",source=\"$source\"}[1m]))",
       "legendFormat": "ticker"
      },
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"trade\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"trade\",source=\"$source\"}[1m]))",
       "legendFormat": "trade"
      },
      {
       "expr": "sum(rate(die_event_handling_time_milliseconds_sum{dataset=\"perpetual\",source=\"$source\"}[1m])) / sum(rate(die_event_handling_time_milliseconds_count{dataset=\"perpetual\",source=\"$source\"}[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "99th percentile",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ticker"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "trade"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"ohlcv\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"ohlcv\"}[1m]))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"ticker\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"ticker\"}[1m]))",
       "legendFormat": "ticker"
      },
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"trade\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"trade\"}[1m]))",
       "legendFormat": "trade"
      },
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"perpetual\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"perpetual\"}[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "99th percentile",
     "type": "graph",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ticker"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "trade"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(collector_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "graph",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"ohlcv\",source=\"$source\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"ohlcv\",source=\"$source\"}[1m]))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"ticker\",source=\"$source\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"ticker\",source=\"$source\"}[1m]))",
       "legendFormat": "ticker"
      },
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"trade\",source=\"$source\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"trade\",source=\"$source\"}[1m]))",
       "legendFormat": "trade"
      },
      {
       "expr": "sum(rate(collector_event_handling_time_milliseconds_sum{dataset=\"perpetual\",source=\"$source\"}[1m])) / sum(rate(collector_event_handling_time_milliseconds_count{dataset=\"perpetual\",source=\"$source\"}[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    }
   ]
  },
  {
   "title": "Writers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "99th percentile",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ticker"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "trade"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"ohlcv\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"ohlcv\",source=\"$source\"}[1m]))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"ticker\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"ticker\",source=\"$source\"}[1m]))",
       "legendFormat": "ticker"
      },
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"trade\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"trade\",source=\"$source\"}[1m]))",
       "legendFormat": "trade"
      },
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"perpetual\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"perpetual\",source=\"$source\"}[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "99th percentile",
     "type": "graph",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "ticker"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "trade"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(writer_total_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\"}[1m])) by (le))",
       "legendFormat": "perpetual"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "graph",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"ohlcv\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"ohlcv\",source=\"$source\"}[1m]))",
       "legendFormat": "ohlcv"
      },
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"ticker\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"ticker\",source=\"$source\"}[1m]))",
       "legendFormat": "ticker"
      },
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"trade\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"trade\",source=\"$source\"}[1m]))",
       "legendFormat": "trade"
      },
      {
       "expr": "sum(rate(writer_total_event_handling_time_milliseconds_sum{dataset=\"perpetual\",source=\"$source\"}[1m])) / sum(rate(writer_total_event_handling_time_milliseconds_count{dataset=\"perpetual\",source=\"$source\"}[1m]))",
       "legendFormat": "perpetual"
      }
     ]
    }
   ]
  },
  {
   "title": "Datasets details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "OHLCV",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "< 50 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"100\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "50 to 100 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"250\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"100\"}[1m]))",
       "legendFormat": "100 to 250 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"250\"}[1m]))",
       "legendFormat": "250 to 500 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"1000\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"500\"}[1m]))",
       "legendFormat": "500 ms to 1 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"2500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"1000\"}[1m]))",
       "legendFormat": "1 s to 2.5 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"+Inf\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\",source=\"$source\",le=\"2500\"}[1m]))",
       "legendFormat": "> 2.5 s"
      }
     ]
    },
    {
     "title": "TICKER",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "< 50 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"100\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "50 to 100 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"250\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"100\"}[1m]))",
       "legendFormat": "100 to 250 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"250\"}[1m]))",
       "legendFormat": "250 to 500 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"1000\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"500\"}[1m]))",
       "legendFormat": "500 ms to 1 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"2500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"1000\"}[1m]))",
       "legendFormat": "1 s to 2.5 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"+Inf\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\",source=\"$source\",le=\"2500\"}[1m]))",
       "legendFormat": "> 2.5 s"
      }
     ]
    },
    {
     "title": "TRADE",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "< 50 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"100\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "50 to 100 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"250\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"100\"}[1m]))",
       "legendFormat": "100 to 250 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"250\"}[1m]))",
       "legendFormat": "250 to 500 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"1000\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"500\"}[1m]))",
       "legendFormat": "500 ms to 1 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"2500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"1000\"}[1m]))",
       "legendFormat": "1 s to 2.5 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"+Inf\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\",source=\"$source\",le=\"2500\"}[1m]))",
       "legendFormat": "> 2.5 s"
      }
     ]
    },
    {
     "title": "PERPETUAL",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "< 50 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"100\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"50\"}[1m]))",
       "legendFormat": "50 to 100 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"250\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"100\"}[1m]))",
       "legendFormat": "100 to 250 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"250\"}[1m]))",
       "legendFormat": "250 to 500 ms"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"1000\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"500\"}[1m]))",
       "legendFormat": "500 ms to 1 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"2500\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"1000\"}[1m]))",
       "legendFormat": "1 s to 2.5 s"
      },
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"+Inf\"}[1m])) - sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\",source=\"$source\",le=\"2500\"}[1m]))",
       "legendFormat": "> 2.5 s"
      }
     ]
    }
   ]
  },
  {
   "title": "Datasets complete details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "OHLCV",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ohlcv\", source=\"$source\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "TICKER",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"ticker\", source=\"$source\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "TRADE",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"trade\", source=\"$source\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "PERPETUAL",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(global_event_handling_time_milliseconds_bucket{dataset=\"perpetual\", source=\"$source\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}