{
 "title": "DIE - Overview",
 "tags": [
  "domains",
  "die",
  "sbt"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cassandra_namespace", "query": "die" },
   {
    "name": "cassandra_datacenter_name",
    "query": "label_values(cassandra_stats{namespace=\"$cassandra_namespace\",name=\"java:lang:memory:heapmemoryusage:used\"}, datacenter)"
   },
   {
    "name": "cassandra_cluster_name",
    "query": "label_values(cassandra_stats{namespace=\"$cassandra_namespace\",datacenter=\"$cassandra_datacenter_name\",name=\"java:lang:memory:heapmemoryusage:used\"}, cluster)"
   },
   { "name": "cassandra_keyspace", "query": "market_data" },
   {
    "name": "cassandra_metric_prefix",
    "query": "org:apache:cassandra:metrics:table"
   },
   { "name": "cassandra_metric_suffix", "query": "writelatency:oneminuterate" },
   { "name": "broker_namespace", "query": "broker" },
   {
    "name": "broker_app_label",
    "query": "label_values(kafka_server_replicamanager_leadercount{namespace=\"$broker_namespace\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "COLLECTORS events rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(collector_trade_event_published_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "COLLECTORS events rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(collector_trade_event_published_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "COLLECTORS events rate stacked",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collector_ohlcv_event_published_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(collector_ticker_event_published_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(collector_trade_event_published_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(collector_perpetual_swap_event_published_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "COLLECTORS error rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(collector_error_event_published_total[1m]))"
    }
   ]
  },
  {
   "title": "KAFKA events rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.ohlcv.sampled\"}[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.ticker.updated\"}[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.trade.executed\"}[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.perpetual.swap.updated\"}[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "KAFKA events rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.ohlcv.sampled\"}[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.ticker.updated\"}[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.trade.executed\"}[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.perpetual.swap.updated\"}[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "KAFKA events rate stacked",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.ohlcv.sampled\"}[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.ticker.updated\"}[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.trade.executed\"}[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{app=\"$broker_app_label\",topic=\"die.perpetual.swap.updated\"}[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "WRITERS events rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(writer_ohlcv_event_saved_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(writer_ticker_event_saved_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(writer_trade_event_saved_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "WRITERS events rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(writer_ohlcv_event_saved_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(writer_ticker_event_saved_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(writer_trade_event_saved_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "WRITERS events rate stacked",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(writer_ohlcv_event_saved_total[1m]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(writer_ticker_event_saved_total[1m]))",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(rate(writer_trade_event_saved_total[1m]))",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(rate(writer_perpetual_swap_event_saved_total[1m]))",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "WRITERS error rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(writer_error_event_saved_total[1m]))"
    }
   ]
  },
  {
   "title": "CASSANDRA writes rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\"})"
    }
   ]
  },
  {
   "title": "CASSANDRA writes rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"ohlcv\"})",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"ticker_updated\"})",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"trade_executed\"})",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"perpetual_swap\"})",
     "legendFormat": "perpetual"
    }
   ]
  },
  {
   "title": "CASSANDRA writes rate stacked",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"ohlcv\"})",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"ticker_updated\"})",
     "legendFormat": "ticker"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"trade_executed\"})",
     "legendFormat": "trade"
    },
    {
     "expr": "sum(cassandra_stats{datacenter=\"$cassandra_datacenter_name\", cluster=\"$cassandra_cluster_name\", name=~\"$cassandra_metric_prefix:$cassandra_keyspace:.*:$cassandra_metric_suffix\", table=\"perpetual_swap\"})",
     "legendFormat": "perpetual"
    }
   ]
  }
 ]
}