{
 "title": "DIE - OHLCV-fillers",
 "tags": [
  "domains",
  "die",
  "sbt"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "exchange",
    "label": "Exchange",
    "query": "label_values(filler_active_ohlcv_computing_cronjobs_number,job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Polling cronjobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(filler_active_ohlcv_computing_cronjobs_number{job=~\".*$exchange\"})"
    }
   ]
  },
  {
   "title": "DB reconnection rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reconn/min" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(filler_db_reconnections_total{job=~\".*$exchange\"}[1h]))"
    }
   ]
  },
  {
   "title": "Queries rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "queries/min" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(filler_ohlcv_queries_total{job=~\".*$exchange\"}[1h]))",
     "legendFormat": "ohlcv"
    },
    {
     "expr": "sum(rate(filler_ticker_queries_total{job=~\".*$exchange\"}[1h]))",
     "legendFormat": "ticker"
    }
   ]
  },
  {
   "title": "Gaps rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gaps/min" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(filler_ohlcv_gaps_found_total{job=~\".*$exchange\"}[1h]))"
    }
   ]
  },
  {
   "title": "Potent. wrong gaps rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gaps/min" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(filler_potential_wrong_ohlcv_zerovolume_gaps_computations_total{job=~\".*$exchange\"}[1h]))"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "OHLCV queries rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "queries/min" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_queries_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "ohlcv-queries-rate"
      }
     ]
    },
    {
     "title": "TICKER queries rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "queries/min" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ticker_queries_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "ticker-queries-rate"
      }
     ]
    }
   ]
  },
  {
   "title": "ZeroVol gaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZeroVol FOUND rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_zerovolume_gaps_found_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "zero-vol-gaps"
      }
     ]
    },
    {
     "title": "ZeroVol COMPUTED rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_zerovolume_gaps_computed_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "zero-vol-gaps"
      }
     ]
    },
    {
     "title": "ZeroVol FILLED rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_zerovolume_gaps_filled_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "zero-vol-gaps"
      }
     ]
    },
    {
     "title": "ZeroVol ERROR rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_zerovolume_gaps_computations_errors_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "zero-vol-gaps"
      }
     ]
    },
    {
     "title": "Potentially wrong ZeroVol gaps rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_potential_wrong_ohlcv_zerovolume_gaps_computations_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "zero-vol-gaps"
      }
     ]
    }
   ]
  },
  {
   "title": "Unexpected gaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unexpected FOUND rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_generic_gaps_found_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "unexpected-gaps"
      }
     ]
    },
    {
     "title": "Unexpected COMPUTED rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_generic_gaps_computed_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "unexpected-gaps"
      }
     ]
    },
    {
     "title": "Unexpected FILLED rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_generic_gaps_filled_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "unexpected-gaps"
      }
     ]
    },
    {
     "title": "Unexpected ERROR rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(filler_ohlcv_generic_gaps_computations_errors_total{job=~\".*$exchange\"}[1h]))",
       "legendFormat": "unexpected-gaps"
      }
     ]
    }
   ]
  }
 ]
}