{
 "title": "DIE - Writers",
 "tags": [
  "domains",
  "die",
  "sbt"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Consuming details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "OHLCV consumed rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_ohlcv_event_consumed_total{job=~\".*-ohlcv\"}[1m]))",
       "legendFormat": "ohlcv-consumed-rate"
      }
     ]
    },
    {
     "title": "OHLCV other rates",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_error_event_consumed_total{job=\"die-data-writer-ohlcv\"}[1m]))",
       "legendFormat": "error"
      },
      {
       "expr": "sum(rate(writer_empty_payload_events_total{job=\"die-data-writer-ohlcv\"}[1m]))",
       "legendFormat": "empty payload"
      }
     ]
    },
    {
     "title": "TICKER consumed rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_ticker_event_consumed_total{job=~\".*-ticker\"}[1m]))",
       "legendFormat": "ticker-consumed-rate"
      }
     ]
    },
    {
     "title": "TICKER other rates",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_error_event_consumed_total{job=\"die-data-writer-ticker\"}[1m]))",
       "legendFormat": "error"
      },
      {
       "expr": "sum(rate(writer_empty_payload_events_total{job=\"die-data-writer-ticker\"}[1m]))",
       "legendFormat": "empty payload"
      }
     ]
    },
    {
     "title": "TRADE consumed rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_trade_event_consumed_total{job=~\".*-trade\"}[1m]))",
       "legendFormat": "trade-consumed-rate"
      }
     ]
    },
    {
     "title": "TRADE other rates",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_error_event_consumed_total{job=\"die-data-writer-trade\"}[1m]))",
       "legendFormat": "error"
      },
      {
       "expr": "sum(rate(writer_empty_payload_events_total{job=\"die-data-writer-trade\"}[1m]))",
       "legendFormat": "empty payload"
      }
     ]
    },
    {
     "title": "PERPETUAL consumed rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(writer_perpetual_swap_event_consumed_total{job=~\".*-trade\"}[1m]))",
       "legendFormat": "perpetual-consumed-rate"
      }
     ]
    },
    {
     "title": "PERPETUAL other rates",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(writer_error_event_consumed_total{job=\"die-data-writer-perpetual\"}[1m]))",
       "legendFormat": "error"
      },
      {
       "expr": "sum(rate(writer_empty_payload_events_total{job=\"die-data-writer-perpetual\"}[1m]))",
       "legendFormat": "empty payload"
      }
     ]
    }
   ]
  },
  { "title": "Saving details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "OHLCV saved rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(writer_ohlcv_event_saved_total{job=~\".*-ohlcv\"}[1m]))",
     "legendFormat": "ohlcv-saved-rate"
    }
   ]
  },
  {
   "title": "OHLCV other rates",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(writer_error_event_saved_total{job=\"die-data-writer-ohlcv\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(writer_event_save_retries_total{job=\"die-data-writer-ohlcv\"}[1m]))",
     "legendFormat": "retries"
    },
    {
     "expr": "sum(rate(writer_event_exceeded_retries_total{job=\"die-data-writer-ohlcv\"}[1m]))",
     "legendFormat": "exceeded save retries"
    }
   ]
  },
  {
   "title": "TICKER saved rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(writer_ticker_event_saved_total{job=~\".*-ticker\"}[1m]))",
     "legendFormat": "ticker-saved-rate"
    }
   ]
  },
  {
   "title": "TICKER other rates",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(writer_error_event_saved_total{job=\"die-data-writer-ticker\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(writer_event_save_retries_total{job=\"die-data-writer-ticker\"}[1m]))",
     "legendFormat": "retries"
    },
    {
     "expr": "sum(rate(writer_event_exceeded_retries_total{job=\"die-data-writer-ticker\"}[1m]))",
     "legendFormat": "exceeded save retries"
    }
   ]
  },
  {
   "title": "TRADE saved rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(writer_trade_event_saved_total{job=~\".*-trade\"}[1m]))",
     "legendFormat": "trade-saved-rate"
    }
   ]
  },
  {
   "title": "TRADE other rates",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(writer_error_event_saved_total{job=\"die-data-writer-trade\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(writer_event_save_retries_total{job=\"die-data-writer-trade\"}[1m]))",
     "legendFormat": "retries"
    },
    {
     "expr": "sum(rate(writer_event_exceeded_retries_total{job=\"die-data-writer-trade\"}[1m]))",
     "legendFormat": "exceeded save retries"
    }
   ]
  },
  {
   "title": "PERPETUAL saved rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(writer_perpetual_swap_event_saved_total{job=~\".*-perpetual\"}[1m]))",
     "legendFormat": "perpetual-saved-rate"
    }
   ]
  },
  {
   "title": "PERPETUAL other rates",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(writer_error_event_saved_total{job=\"die-data-writer-perpetual\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(writer_event_save_retries_total{job=\"die-data-writer-perpetual\"}[1m]))",
     "legendFormat": "retries"
    },
    {
     "expr": "sum(rate(writer_event_exceeded_retries_total{job=\"die-data-writer-perpetual\"}[1m]))",
     "legendFormat": "exceeded save retries"
    }
   ]
  }
 ]
}