
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argo-cd-metrics.yaml
  - argo-cd-repo-server-metrics.yaml
  - argo-cd-server-metrics.yaml

commonLabels:
  app: argo-cd
  domain: cicd
  feature: monitoring
