apiVersion: v1
kind: Service
metadata:
  name: rollout-canary
  namespace: argo-rollouts
spec:
  selector:
    app: rollout-canary
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
