{
 "title": "Consul",
 "tags": [
  "support",
  "consul"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_up" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_serf_lan_members" }
   ]
  },
  {
   "title": "Leaders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_raft_leader" }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_raft_peers" }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{status=\"critical\"})"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{status=\"warning\"})"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(consul_health_node_status{status=\"maintenance\"})"
    }
   ]
  },
  {
   "title": "General status",
   "type": "table",
   "description": "Available status: passing, warning, maintenance, critical",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "consul_health_node_status > 0" }
   ]
  },
  {
   "title": "Cluster status",
   "type": "table",
   "description": "Status of member in the cluster:   1 = Alive,   2 = Leaving,   3 = Left,   4 = Failed",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "consul_serf_lan_member_status" }
   ]
  },
  {
   "title": "General status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(consul_health_node_status) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "graph",
   "description": "Status of member in the cluster:   1 = Alive,   2 = Leaving,   3 = Left,   4 = Failed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_serf_lan_member_status", "legendFormat": "{{ member }}" }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "consul_catalog_services" }
     ]
    },
    {
     "title": "Services/Nodes",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 3, "y": 20 },
     "targets": [
      {
       "expr": "consul_catalog_service_node_healthy"
      }
     ]
    },
    {
     "title": "Services/Nodes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(consul_catalog_service_node_healthy) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  }
 ]
}