
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager.yaml
  - alertmanagerConfig.yaml
  - podmonitor.yaml
  - probe.yaml
  - prometheus.yaml
  - prometheusrule.yaml
  - servicemonitor.yaml
  - thanosruler.yaml

commonLabels:
  app: prometheus-operator
  domain: monitoring
  group: crds

commonAnnotations:
  version: v0.44.0
  argocd.argoproj.io/sync-wave: "1"
