
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-metrics.yaml
  - go-metrics.yaml
  - grafana.yaml
  - guestbook.yaml
  - guestbook-private.yaml
  - postgres.yaml
  - prometheus.yaml
