{
 "title": "Calico",
 "tags": [
  "networking",
  "calico"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "typha",
    "label": "Typha node",
    "query": "label_values(container_cpu_usage_seconds_total{pod=~\"calico-typha-.*\", container=\"calico-typha\"},pod)"
   },
   {
    "name": "felix",
    "label": "Felix host",
    "query": "label_values(container_cpu_usage_seconds_total{pod=~\"calico-node-.*\", container=\"calico-node\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Typha nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(typha_ping_latency_count)"
    }
   ]
  },
  {
   "title": "ipset errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_ipset_errors[5m]))"
    }
   ]
  },
  {
   "title": "iptables save errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_save_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "iptables restore errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_restore_errors[5m]))"
    }
   ]
  },
  {
   "title": "Felix active endpoints",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "expr": "felix_active_local_endpoints" }
   ]
  },
  {
   "title": "Felix cluster policies",
   "type": "table",
   "description": "More policies on Felix means more effort required by Calico to manage packets. ",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "felix_cluster_num_policies" }
   ]
  },
  {
   "title": "Felix hosts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(felix_host)" }
   ]
  },
  {
   "title": "Felix resync started",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_resyncs_started[5m])) "
    }
   ]
  },
  {
   "title": "Felix log errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(felix_log_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Typha resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{pod=~\"$typha\", container=\"calico-typha\"}[1m])",
       "legendFormat": "Current: {{ pod }}"
      },
      {
       "expr": "kube_pod_container_resource_requests{pod=~\"$typha\", container=\"calico-typha\"}",
       "legendFormat": "Requested: {{ pod }}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~\"$typha\", container=\"calico-typha\"}",
       "legendFormat": "Current: {{ pod }}"
      },
      {
       "expr": "kube_pod_container_resource_requests{pod=~\"$typha\", container=\"calico-typha\"}",
       "legendFormat": "Requested: {{ pod }}"
      },
      {
       "expr": "kube_pod_container_resource_limits{pod=~\"$typha\", container=\"calico-typha\"}",
       "legendFormat": "Limit: {{ pod }}"
      },
      {
       "expr": "container_memory_cache{pod=~\"$typha\", container=\"calico-typha\"}",
       "legendFormat": "Cache: {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Felix resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{pod=~\"$felix\", container=\"calico-node\"}[1m])",
       "legendFormat": "Current: {{ pod }}"
      },
      {
       "expr": "kube_pod_container_resource_requests{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "Requested: {{ pod }}"
      },
      {
       "expr": "kube_pod_container_resource_limits{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "Limit: {{ pod }}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "Current: {{ pod }}"
      },
      {
       "expr": "kube_pod_container_resource_requests{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "Requested: {{ pod }}"
      },
      {
       "expr": "kube_pod_container_resource_limits{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "Limit: {{ pod }}"
      },
      {
       "expr": "container_memory_cache{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "Cache: {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dropped logs",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_logs_dropped{pod=~\"$felix\", container=\"calico-node\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "This graph shows you all the errors that Calico encounters, it is important to note occasional errors are acceptable. However, rise in the number of error or constant error counters means Calico is not working properly.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_ipset_errors{pod=~\"$felix\", container=\"calico-node\"}[5m])",
       "legendFormat": "{{ pod }} ipset errors"
      },
      {
       "expr": "rate(felix_iptables_restore_errors{pod=~\"$felix\", container=\"calico-node\"}[5m])",
       "legendFormat": "{{ pod }} iptables restore errors"
      },
      {
       "expr": "rate(felix_iptables_save_errors{pod=~\"$felix\", container=\"calico-node\"}[5m])",
       "legendFormat": "{{ pod }} iptables save errors"
      },
      {
       "expr": "rate(felix_log_errors{pod=~\"$felix\", container=\"calico-node\"}[5m])",
       "legendFormat": "{{ pod }} log errors"
      }
     ]
    },
    {
     "title": "Exec time p50",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(felix_exec_time_micros{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.5\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Exec time p90",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(felix_exec_time_micros{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.9\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Exec time p99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "rate(felix_exec_time_micros{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.99\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Active endpoints",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "felix_active_local_endpoints{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Active policies",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "felix_active_local_policies{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Active selectors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "felix_active_local_selectors{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Active IP sets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "felix_ipsets_calico{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Active local tags",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "felix_active_local_tags{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Cluster host endpoints",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "felix_cluster_num_host_endpoints{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Cluster workload endpoints",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "felix_cluster_num_workload_endpoints{pod=~\"$felix\", container=\"calico-node\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataplane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apply time p50",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(felix_int_dataplane_apply_time_seconds{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.5\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Apply time p90",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(felix_int_dataplane_apply_time_seconds{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.9\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Apply time duration p99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(felix_int_dataplane_apply_time_seconds{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.99\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Total failures",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(felix_int_dataplane_failures[5m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Failures per pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(felix_int_dataplane_failures{pod=~\"$felix\", container=\"calico-node\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Message batch Sizes p50",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_int_dataplane_msg_batch_size{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.5\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Message batch Sizes p90",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_int_dataplane_msg_batch_size{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.9\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Message batch Sizes p99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_int_dataplane_msg_batch_size{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.99\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Message types",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(felix_int_dataplane_messages[5m])) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Route table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Route table list p50",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_route_table_list_seconds{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.5\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Route table list p90",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_route_table_list_seconds{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.9\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Route table list p99",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(felix_route_table_list_seconds{pod=~\"$felix\", container=\"calico-node\", quantile=\"0.99\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "iptables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active chains",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(felix_iptables_chains) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Active rules",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(felix_iptables_rules) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Lines executed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(felix_iptables_lines_executed[5m])) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Calls",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(felix_iptables_save_calls[5m]))",
       "legendFormat": "Save"
      },
      {
       "expr": "sum(rate(felix_iptables_restore_calls[5m]))",
       "legendFormat": "Restore"
      }
     ]
    },
    {
     "title": "Save errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(felix_iptables_save_errors{pod=~\"$felix\", container=\"calico-node\"}[5m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Restore errors",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(felix_iptables_restore_errors{pod=~\"$felix\", container=\"calico-node\"}[5m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}