{
 "title": "Traefik",
 "tags": [
  "traefik",
  "networking"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "query": "traefik-api" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,15m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentiles", "label": "Percentiles", "query": "95,99" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=\"networking\",condition=\"true\",pod=~\"traefik.*\"})"
    }
   ]
  },
  {
   "title": "Total uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - sum(process_start_time_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "GET : 4xx over $interval",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"4.*\",method=\"GET\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GET : 5xx over $interval",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"5.*\",method=\"GET\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total open connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections)",
     "legendFormat": "open conn"
    }
   ]
  },
  {
   "title": "Entrypoint requests rate over $interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(traefik_entrypoint_requests_total[$interval]))",
     "legendFormat": "Entrypoint rate"
    }
   ]
  },
  {
   "title": "Service requests rate over $interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(traefik_service_requests_total[$interval])) by (exported_service), \"svc\", \"$1\", \"exported_service\", \"(.*)@kubernetes\")",
     "legendFormat": "{{ svc }}"
    }
   ]
  },
  {
   "title": "Global latency [$percentiles th perc over 5 min]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(irate(traefik_entrypoint_request_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "Global latency"
    }
   ]
  },
  {
   "title": "Return codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "GET : 2xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"2..\",method=\"GET\"}[$interval]))"
      }
     ]
    },
    {
     "title": "GET : 3xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"3..\",method=\"GET\"}[$interval]))"
      }
     ]
    },
    {
     "title": "GET : 4xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"4..\",method=\"GET\"}[$interval]))"
      }
     ]
    },
    {
     "title": "GET : 5xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"5..\",method=\"GET\"}[$interval]))"
      }
     ]
    },
    {
     "title": "All status codes over $interval",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(traefik_entrypoint_requests_total[$interval])) by (method, code)",
       "legendFormat": "{{ method }} : {{ code }}"
      }
     ]
    },
    {
     "title": "POST : 2xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"2..\",method=\"POST\"}[$interval]))"
      }
     ]
    },
    {
     "title": "POST : 3xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"3..\",method=\"POST\"}[$interval]))"
      }
     ]
    },
    {
     "title": "POST : 4xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"4..\",method=\"POST\"}[$interval]))"
      }
     ]
    },
    {
     "title": "POST : 5xx over $interval",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"5..\",method=\"POST\"}[$interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entrypoint average response time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "traefik_entrypoint_request_duration_seconds_sum / traefik_entrypoint_requests_total * 1000",
       "legendFormat": "{{ method }} : {{ code }}"
      }
     ]
    },
    {
     "title": "Entrypoint apdex score over $interval",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.1\"}[$interval])) by (method) / sum(irate(traefik_entrypoint_request_duration_seconds_count[$interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Service average response time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "traefik_service_request_duration_seconds_sum / traefik_service_requests_total * 1000",
       "legendFormat": "{{ method }} : {{ code }}"
      }
     ]
    },
    {
     "title": "Service apdex score over $interval",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(traefik_service_request_duration_seconds_bucket{le=\"0.1\"}[$interval])) by (method) / sum(irate(traefik_service_request_duration_seconds_count[$interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open connections by service",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(traefik_service_open_connections) by (exported_service), \"svc\", \"$1\", \"exported_service\", \"(.*)@kubernetes\")",
       "legendFormat": "{{ svc }}"
      }
     ]
    },
    {
     "title": "Open connections by method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by service",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "label_replace(sum(irate(traefik_service_requests_total[$interval])) by (exported_service), \"svc\", \"$1\", \"exported_service\", \"(.*)@kubernetes\")",
       "legendFormat": "{{ svc }}"
      }
     ]
    },
    {
     "title": "Requests by protocol",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(irate(traefik_entrypoint_requests_total[$interval])) by (entrypoint)",
       "legendFormat": "{{ entrypoint }}"
      }
     ]
    },
    {
     "title": "Requests by return code",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(traefik_service_requests_total[$interval])) by (method, code)",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    }
   ]
  }
 ]
}