{
 "title": "GCP - GCE VMs",
 "tags": [
  "cloud",
  "gcp",
  "gce"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "stackdriver" },
   {
    "name": "project",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GCE VM Instance - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "compute.googleapis.com/instance/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "unit": "10^2.%",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "GCE VM Instance - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.instance_name}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/uptime",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "s{uptime}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/instance/disk/read_ops_count",
        "perSeriesAligner": "ALIGN_RATE",
        "projectName": "$project",
        "unit": "1",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Disk write operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/instance/disk/write_ops_count",
        "perSeriesAligner": "ALIGN_DELTA",
        "projectName": "$project",
        "unit": "1",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Disk read bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/instance/disk/read_bytes_count",
        "perSeriesAligner": "ALIGN_DELTA",
        "projectName": "$project",
        "unit": "By",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Disk write bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/instance/disk/write_bytes_count",
        "perSeriesAligner": "ALIGN_DELTA",
        "projectName": "$project",
        "unit": "By",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "GCE VM Instance - Received packets count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/instance/network/received_packets_count",
        "perSeriesAligner": "ALIGN_DELTA",
        "projectName": "$project",
        "unit": "1",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "GCE VM Instance - Sent packets count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/nat/sent_packets_count",
        "perSeriesAligner": "ALIGN_DELTA",
        "projectName": "$project",
        "unit": "{packet}",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "GCE VM Instance - Received bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/instance/network/received_bytes_count",
        "perSeriesAligner": "ALIGN_DELTA",
        "projectName": "$project",
        "unit": "By",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "GCE VM Instance - Sent bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{metric.label.instance_name}}",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "compute.googleapis.com/instance/network/sent_bytes_count",
        "perSeriesAligner": "ALIGN_DELTA",
        "projectName": "$project",
        "unit": "By",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  }
 ]
}