{
 "title": "MongoDB",
 "description": "MongoDB dashboard for metrics exported by Prometheus",
 "tags": [
  "databases",
  "mongodb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace:",
    "query": "label_values(mongodb_connections, namespace)"
   },
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(mongodb_connections{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "interval",
    "label": "Interval:",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{namespace=\"$namespace\",pod=\"$node\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{namespace=\"$namespace\",pod=\"$node\",state=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_connections{namespace=\"$namespace\",pod=\"$node\",state=\"current\"}"
    }
   ]
  },
  {
   "title": "Faults rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
     "legendFormat": "faults"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_op_latencies_latency_total",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Document ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "TTL activities",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
     "legendFormat": "deleted"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_passes_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
     "legendFormat": "passes"
    }
   ]
  },
  {
   "title": "ReplicaSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Member Health",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_number_of_members{namespace=\"$namespace\",pod=\"$node\"}",
       "legendFormat": "# members"
      },
      {
       "expr": "sum(mongodb_replset_member_health{namespace=\"$namespace\",pod=\"$node\"})",
       "legendFormat": "healthy members"
      }
     ]
    },
    {
     "title": "Member State",
     "type": "graph",
     "description": "See which node is currently acting as the primary, secondary, ...",
     "gridPos": { "h": 6, "w": 12, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_member_state{namespace=\"$namespace\",pod=\"$node\"}",
       "legendFormat": "{{ state }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Replica Query Operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_repl_total{namespace=\"$namespace\",pod=\"$node\"}[$interval])",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Oplog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_replset_oplog_size_bytes{namespace=\"$namespace\",pod=\"$node\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Oplog Lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_replset_oplog_head_timestamp[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}