{
 "title": "NATS Server",
 "description": "NATS Server dashboard",
 "tags": [
  "brokers",
  "nats"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nats_varz_cpu", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nats_varz_mem", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nats_varz_in_bytes", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "Bytes Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nats_varz_out_bytes", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "NATS Msgs In",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nats_varz_in_msgs", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "NATS Msgs Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nats_varz_out_msgs", "legendFormat": "{{ pod }}" }
     ]
    }
   ]
  },
  {
   "title": "Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nats_varz_connections", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "Subscriptions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nats_varz_subscriptions", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "Slow Consumers",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nats_varz_slow_consumers", "legendFormat": "{{ pod }}" }
     ]
    }
   ]
  }
 ]
}